# Generated by Django 3.2.8 on 2021-12-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_doc', models.CharField(help_text='Tipo de documento', max_length=2, verbose_name='Tipo de documento')),
                ('num_doc', models.CharField(help_text='Numero de documento', max_length=12, verbose_name='Numero de documento')),
                ('nombres', models.CharField(help_text='Nombres del cliente', max_length=25, verbose_name='Nombres del cliente')),
                ('apellidos', models.CharField(max_length=25, verbose_name='Apellidos del cliente')),
                ('total_items', models.IntegerField()),
                ('total_factura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('categoria', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('unidad_medida', models.CharField(max_length=15)),
                ('undidades_disponibles', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemsFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidades', models.IntegerField()),
                ('precio', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='appTienda.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='appTienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
